using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SSDK.Benchmarking
{
    /// <summary>
    /// Contains methods for generating numbers
    /// </summary>
    public static class NumberGenerator
    {
        /// <summary>
        /// The random number generator
        /// </summary>
        private static Random RG = new Random();

        /// <summary>
        /// Creates any number (< int.maxValue) of integers as an array,
        /// all generated by a random number generator.
        /// </summary>
        /// <param name="count">the number of integers to generate</param>
        /// <returns>an array of integers which the given count</returns>
        public static int[] CreateRandomIntegers(int count)
        {
            int[] result = new int[count];
            // Generate random numbers
            for(int i = 0; i<count; i++)
            {
                result[i] = RG.Next(int.MinValue, int.MaxValue) + RG.Next(0, 2);
            }
            return result;
        }

        
    }
}
